name: Latest github activity
on:
  schedule:
    # Runs twice a week
    - cron: '0 0 * * */3'
  workflow_dispatch:

jobs:
  update-readme-with-stack-overflow:
    name: Update this repo's README with latest activity from StackOverflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{}}